 'use strict';
const assert=require('assert');
const server=require('../desktop-app/server.js');
const {UnifiedScanPipeline}=require('../desktop-app/unified-scan-pipeline.js');
assert(server.modelPipeline instanceof UnifiedScanPipeline);
assert.equal(server.sandbox, undefined);
assert.equal(server.cloudInspection, undefined);
assert.equal(server.gtaCloudSimulation, undefined);
assert(!Object.keys(require.cache).some(file=>/[/\\]sandbox[/\\](sandbox-controller|isolation-backend-router)\.js$/.test(file)));
console.log('✓ GTA Guard runtime does not instantiate or import an execution backend');
