 'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const html=fs.readFileSync(path.join(__dirname,'../desktop-app/public/index.html'),'utf8');
const js=fs.readFileSync(path.join(__dirname,'../desktop-app/public/app.js'),'utf8');
assert.doesNotMatch(html, /id="(?:scanModel|cloudFallback|aiEvidence|finalSandboxTest)"/);
assert.doesNotMatch(html, /sandbox-first-run\.js/);
assert.match(html, /id="cancelScan"/);
assert.match(html, /id="modelDiagnostics"/);
assert.match(html, /cannot prove a file is safe/);
assert.match(js, /\/api\/model-scan\/cancel/);
assert.doesNotMatch(js, /\/api\/sandbox\//);
assert.match(js, /This scan has not quarantined or blocked it/);
console.log('✓ Unified UI: single scan, cancellation, explicit limitations and no execution controls PASS');
