'use strict';
const assert = require('assert');
const path = require('path');
const { spawnSync } = require('child_process');
const result = spawnSync(process.execPath, [path.join(__dirname, '../tools/verify-product-readiness.js')], {encoding:'utf8',timeout:30000,windowsHide:true});
if(result.error)throw result.error;
assert.equal(result.status,0,result.stdout+'\n'+result.stderr);
const report=JSON.parse(result.stdout);
assert.equal(report.scope,'unified_static_product_contract');
assert.equal(report.executionMode,'static_only');
assert.equal(report.unknownIsSafe,false);
assert.equal(report.dynamicAnalysis,'disabled');
assert.equal(report.productReleaseReady,false,'source checks alone must not claim release readiness');
assert.equal(report.safety.untrustedSamplesExecuted,false);
console.log('✓ Product contract gate: static-only, unknown != safe, no fabricated release readiness PASS');
