plugins {
    id 'com.android.application'
}

android {
    namespace 'com.malguard.mobilepreview'
    compileSdk 35

    defaultConfig {
        applicationId 'com.malguard.mobilepreview'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1.0-preview'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
